[tool.poetry]
name = "csrf-exploit"
version = "0.1.0"
description = ""
authors = ["Andreas Schmitz <andreas@wirbauen.digital>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.0"
httpx = "^0.23.0"
Pillow = "^9.2.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
